- hosts: web
  vars:
    servers: [{name: webserver1, settings: {ip: 192.168.1.1, role: web, ports: [80, 443]}}, {name: dbserver, settings: {ip: 192.168.1.2, role: database, ports: [3306]}}]
  tasks:
    - name: show info
      debug:
        msg: "Server {{item.name}} (ip: {{item.settings.ip}}) with {{item.settings.role}} will open ports: {{item.settings.ports | join(',')}}"
      loop: "{{servers}}"
