- name: Mount NFS share on Ubuntu
  hosts: db
  become: yes  # 관리자 권한으로 실행
  tasks:
    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Create mount point directory
      file:
        path: /mnt/nfs_share  # 마운트할 디렉토리 경로
        state: directory
        mode: '0755'

    - name: Mount NFS share
      mount:
        path: /mnt/nfs_share  # 마운트할 디렉토리
        src: "192.168.30.1:/path/to/share"  # NFS 서버 및 공유 디렉토리
        fstype: nfs
        opts: rw,sync  # 마운트 옵션 (읽기/쓰기, 동기화)
        state: mounted

    - name: Ensure NFS mount is persistent across reboots
      mount:
        path: /mnt/nfs_share
        src: "192.168.30.1:/path/to/share"
        fstype: nfs
        opts: rw,sync
        state: mounted
        dump: 0
        passno: 0
