- name: Install and configure Nginx with 2 virtual hosts on Ubuntu
  hosts: web
  become: yes
  tasks:
    # 1. Nginx 설치
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    # 2. 두 개의 가상 서버 설정 파일을 생성
    - name: Create conf naver.com
      copy:
        dest: /etc/nginx/sites-available/naver.com
        content: |
          server {
              listen 80;
              server_name www.naver.com;

              root /usr/share/nginx/html/naver;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
    
    - name: Create conf google.com
      copy:
        dest: /etc/nginx/sites-available/google.com
        content: |
          server {
              listen 80;
              server_name www.google.com;

              root /usr/share/nginx/html/google;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    # 3. 가상 서버를 sites-enabled에 심볼릭 링크 생성
    - name: Enable naver.com site
      file:
        src: /etc/nginx/sites-available/naver.com
        dest: /etc/nginx/sites-enabled/naver.com
        state: link

    - name: Enable google.com site
      file:
        src: /etc/nginx/sites-available/google.com
        dest: /etc/nginx/sites-enabled/google.com
        state: link

    # 4. 웹 콘텐츠 디렉토리 생성
    - name: Create directory for naver.com
      file:
        path: /usr/share/nginx/html/naver
        state: directory

    - name: Create directory for google.com
      file:
        path: /usr/share/nginx/html/google
        state: directory

    # 5. 각 도메인에 대한 기본 index.html 파일 생성
    - name: Create index.html for naver.com
      copy:
        dest: /usr/share/nginx/html/naver/index.html
        content: "<body style='backgroud-color:ffbcbc'>Welcome to naver.com</body>"
    
    - name: Create index.html for google.com
      copy:
        dest: /usr/share/nginx/html/google/index.html
        content: "<body style='backgroud-color:bcffbc'>Welcome to google.com</body>"


    # 6. Nginx 구문 테스트
    - name: Test nginx configuration
      command: nginx -t

    # 7. Nginx 재시작
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
