- name: Mount to Samba server in Ubuntu
  hosts: db
  become: yes
  tasks:
    - name: Install cifs-utils 
      apt:
        name: cifs-utils
        state: present
        update_cache: yes

    - name: Create mount directory
      file:
        path: /dir2
        state: directory
        mode: '0755'

    - name: Samba share
      mount:
        path: /dir2
        src: //192.168.20.1/humans
        fstype: cifs
        opts: "username=user1,password=Test123!"
        state: mounted
        dump: 0
        passno: 0

    - name: Samba info check
      shell: mount | grep /dir2
      register: mount_status
      changed_when: False

    - name: Show state
      debug:
        msg: "Mounted Samba: {{ mount_status.stdout }}"
